<?php
$productCollection = Mage::getModel('catalog/product')->getCollection();
$productCollection->addAttributeToSelect(array('image','name','final_price','price','old_price'))
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   ))->addFinalPrice()->getSelect()->where('price_index.final_price < price_index.price');

Mage::getModel('review/review')->appendSummary($productCollection);
$_helper = $this->helper('catalog/output');
?>
<?php if(!$productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php // Product Grid ?>
            <?php $iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($productCollection as $product):
                    $AddToCartUrl = Mage::helper('checkout/cart')->getAddUrl($product);?>
                    <li class="item<?php if( ++$iterator == sizeof($productCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $product->getImageUrl(); ?>" width="100" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $productNameStripped = $this->stripTags($product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $productNameStripped; ?>"><?php echo $_helper->productAttribute($product, $product->getName() , 'name'); ?></a></h2>
                                <?php if($product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($product) ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($product, true) ?>
                                <?php if($product->isSaleable()): ?>

                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $AddToCartUrl ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="special-price">
                                    <?php 
                                        $price = $product->getPrice();
                                        $specialPrice = $product->getFinalPrice();
                                            if($specialPrice < $price): ?>
                                     <?php 
                                         $savePercent = 100 - round(($specialPrice / $price) * 100);
                                         $specialPriceAmount = number_format(($specialPrice), 2);   
                                         $saveAmount = number_format(($price - $specialPrice), 2);   ?> 
                                        <span class="price-box">
                                            <p class="old-price">
                                                <span class="price">
                                                    $<?php echo number_format(($price), 2); ?>
                                                </span>
                                            </p> &nbsp;&nbsp;
                                        <span class="final-price">
                                            $<?php echo $specialPriceAmount ?>
                                        </span>
                                            <div>
                                    You Save : <span class="offer">
                                                    $<?php echo $saveAmount?>
                                                    (<?php echo $savePercent; ?>% off)   
                                                </span>
                                            </div>
                                    <?php endif; ?>
                                </div>
                                <div class="desc std">       
                                    <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                                <ul class="add-to-links" style="margin:0; padding-left:0; list-style: none;">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')
            </script>
    </div>
<?php endif; ?>


